#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require 'optparse'
require "ruby_script_exporter"

options = RubyScriptExporter::Util.parse_options

RubyScriptExporter::Server.set :port, options[:port]
RubyScriptExporter::Server.set :bind , options[:host]
RubyScriptExporter::Server.run!
